/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ProofLayerDecisionLog {
      
    export type DecisionStruct = {decisionId: BytesLike, certificateId: BytesLike, actor: AddressLike, actionType: BytesLike, allowed: boolean, timestamp: BigNumberish}

    export type DecisionStructOutput = [decisionId: string, certificateId: string, actor: string, actionType: string, allowed: boolean, timestamp: bigint] & {decisionId: string, certificateId: string, actor: string, actionType: string, allowed: boolean, timestamp: bigint }
  
    }

  export interface ProofLayerDecisionLogInterface extends Interface {
    getFunction(nameOrSignature: "authorizedWriters" | "decisionCount" | "decisionExists" | "getDecision" | "owner" | "recordDecision" | "setWriterAuthorization" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DecisionRecorded" | "OwnershipTransferred" | "WriterAuthorizationUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'authorizedWriters', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'decisionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'decisionExists', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getDecision', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordDecision', values: [BytesLike, BytesLike, AddressLike, BytesLike, boolean]): string;
encodeFunctionData(functionFragment: 'setWriterAuthorization', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'authorizedWriters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decisionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decisionExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDecision', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordDecision', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWriterAuthorization', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace DecisionRecordedEvent {
      export type InputTuple = [decisionId: BytesLike, certificateId: BytesLike, actor: AddressLike, actionType: BytesLike, allowed: boolean, timestamp: BigNumberish];
      export type OutputTuple = [decisionId: string, certificateId: string, actor: string, actionType: string, allowed: boolean, timestamp: bigint];
      export interface OutputObject {decisionId: string, certificateId: string, actor: string, actionType: string, allowed: boolean, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WriterAuthorizationUpdatedEvent {
      export type InputTuple = [writer: AddressLike, authorized: boolean];
      export type OutputTuple = [writer: string, authorized: boolean];
      export interface OutputObject {writer: string, authorized: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ProofLayerDecisionLog extends BaseContract {
    
    connect(runner?: ContractRunner | null): ProofLayerDecisionLog;
    waitForDeployment(): Promise<this>;

    interface: ProofLayerDecisionLogInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    authorizedWriters: TypedContractMethod<
      [writer: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    decisionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    decisionExists: TypedContractMethod<
      [decisionId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getDecision: TypedContractMethod<
      [decisionId: BytesLike, ],
      [ProofLayerDecisionLog.DecisionStructOutput],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recordDecision: TypedContractMethod<
      [decisionId: BytesLike, certificateId: BytesLike, actor: AddressLike, actionType: BytesLike, allowed: boolean, ],
      [string],
      'nonpayable'
    >
    

    
    setWriterAuthorization: TypedContractMethod<
      [writer: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'authorizedWriters'): TypedContractMethod<
      [writer: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'decisionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decisionExists'): TypedContractMethod<
      [decisionId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getDecision'): TypedContractMethod<
      [decisionId: BytesLike, ],
      [ProofLayerDecisionLog.DecisionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recordDecision'): TypedContractMethod<
      [decisionId: BytesLike, certificateId: BytesLike, actor: AddressLike, actionType: BytesLike, allowed: boolean, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWriterAuthorization'): TypedContractMethod<
      [writer: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DecisionRecorded'): TypedContractEvent<DecisionRecordedEvent.InputTuple, DecisionRecordedEvent.OutputTuple, DecisionRecordedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'WriterAuthorizationUpdated'): TypedContractEvent<WriterAuthorizationUpdatedEvent.InputTuple, WriterAuthorizationUpdatedEvent.OutputTuple, WriterAuthorizationUpdatedEvent.OutputObject>;

    filters: {
      
      'DecisionRecorded(bytes32,bytes32,address,bytes32,bool,uint64)': TypedContractEvent<DecisionRecordedEvent.InputTuple, DecisionRecordedEvent.OutputTuple, DecisionRecordedEvent.OutputObject>;
      DecisionRecorded: TypedContractEvent<DecisionRecordedEvent.InputTuple, DecisionRecordedEvent.OutputTuple, DecisionRecordedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'WriterAuthorizationUpdated(address,bool)': TypedContractEvent<WriterAuthorizationUpdatedEvent.InputTuple, WriterAuthorizationUpdatedEvent.OutputTuple, WriterAuthorizationUpdatedEvent.OutputObject>;
      WriterAuthorizationUpdated: TypedContractEvent<WriterAuthorizationUpdatedEvent.InputTuple, WriterAuthorizationUpdatedEvent.OutputTuple, WriterAuthorizationUpdatedEvent.OutputObject>;
    
    };
  }