/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ProofLayerMarketAdapterInterface extends Interface {
    getFunction(nameOrSignature: "balances" | "deposit" | "policyGate" | "poolBalance" | "validateCertificate" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposited" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'balances', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'policyGate', values?: undefined): string;
encodeFunctionData(functionFragment: 'poolBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'validateCertificate', values: [BytesLike, BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish, BytesLike, BytesLike, BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'balances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'policyGate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'poolBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace DepositedEvent {
      export type InputTuple = [actor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [actor: string, amount: bigint];
      export interface OutputObject {actor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [actor: AddressLike, amount: BigNumberish, decisionId: BytesLike];
      export type OutputTuple = [actor: string, amount: bigint, decisionId: string];
      export interface OutputObject {actor: string, amount: bigint, decisionId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ProofLayerMarketAdapter extends BaseContract {
    
    connect(runner?: ContractRunner | null): ProofLayerMarketAdapter;
    waitForDeployment(): Promise<this>;

    interface: ProofLayerMarketAdapterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balances: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    policyGate: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    poolBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    validateCertificate: TypedContractMethod<
      [certificateId: BytesLike, assetId: BytesLike, claimType: BytesLike, policyId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [amount: BigNumberish, certificateId: BytesLike, assetId: BytesLike, claimType: BytesLike, policyId: BytesLike, ],
      [string],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balances'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'policyGate'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'poolBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'validateCertificate'): TypedContractMethod<
      [certificateId: BytesLike, assetId: BytesLike, claimType: BytesLike, policyId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [amount: BigNumberish, certificateId: BytesLike, assetId: BytesLike, claimType: BytesLike, policyId: BytesLike, ],
      [string],
      'nonpayable'
    >;

    getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'Deposited(address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'Withdrawn(address,uint256,bytes32)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }