/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ProofLayerCertificateRegistry {
      
    export type CertificateStruct = {certificateId: BytesLike, assetId: BytesLike, claimType: BytesLike, policyId: BytesLike, evidenceRoot: BytesLike, observedAt: BigNumberish, validUntil: BigNumberish, independentRootCount: BigNumberish, result: BigNumberish, issuer: AddressLike, revoked: boolean}

    export type CertificateStructOutput = [certificateId: string, assetId: string, claimType: string, policyId: string, evidenceRoot: string, observedAt: bigint, validUntil: bigint, independentRootCount: bigint, result: bigint, issuer: string, revoked: boolean] & {certificateId: string, assetId: string, claimType: string, policyId: string, evidenceRoot: string, observedAt: bigint, validUntil: bigint, independentRootCount: bigint, result: bigint, issuer: string, revoked: boolean }
  
    }

  export interface ProofLayerCertificateRegistryInterface extends Interface {
    getFunction(nameOrSignature: "RESULT_FAIL" | "RESULT_INDETERMINATE" | "RESULT_PASS" | "authorizedIssuers" | "certificateExists" | "getCertificate" | "isCertificateUsable" | "owner" | "registerCertificate" | "revokeCertificate" | "setIssuerAuthorization" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CertificateRegistered" | "CertificateRevoked" | "IssuerAuthorizationUpdated" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'RESULT_FAIL', values?: undefined): string;
encodeFunctionData(functionFragment: 'RESULT_INDETERMINATE', values?: undefined): string;
encodeFunctionData(functionFragment: 'RESULT_PASS', values?: undefined): string;
encodeFunctionData(functionFragment: 'authorizedIssuers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'certificateExists', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getCertificate', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isCertificateUsable', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerCertificate', values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeCertificate', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'setIssuerAuthorization', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'RESULT_FAIL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RESULT_INDETERMINATE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RESULT_PASS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedIssuers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'certificateExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isCertificateUsable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setIssuerAuthorization', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace CertificateRegisteredEvent {
      export type InputTuple = [certificateId: BytesLike, assetId: BytesLike, policyId: BytesLike, claimType: BytesLike, evidenceRoot: BytesLike, observedAt: BigNumberish, validUntil: BigNumberish, independentRootCount: BigNumberish, result: BigNumberish, issuer: AddressLike];
      export type OutputTuple = [certificateId: string, assetId: string, policyId: string, claimType: string, evidenceRoot: string, observedAt: bigint, validUntil: bigint, independentRootCount: bigint, result: bigint, issuer: string];
      export interface OutputObject {certificateId: string, assetId: string, policyId: string, claimType: string, evidenceRoot: string, observedAt: bigint, validUntil: bigint, independentRootCount: bigint, result: bigint, issuer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CertificateRevokedEvent {
      export type InputTuple = [certificateId: BytesLike, revokedBy: AddressLike];
      export type OutputTuple = [certificateId: string, revokedBy: string];
      export interface OutputObject {certificateId: string, revokedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IssuerAuthorizationUpdatedEvent {
      export type InputTuple = [issuer: AddressLike, authorized: boolean];
      export type OutputTuple = [issuer: string, authorized: boolean];
      export interface OutputObject {issuer: string, authorized: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ProofLayerCertificateRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ProofLayerCertificateRegistry;
    waitForDeployment(): Promise<this>;

    interface: ProofLayerCertificateRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    RESULT_FAIL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    RESULT_INDETERMINATE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    RESULT_PASS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    authorizedIssuers: TypedContractMethod<
      [issuer: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    certificateExists: TypedContractMethod<
      [certificateId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getCertificate: TypedContractMethod<
      [certificateId: BytesLike, ],
      [ProofLayerCertificateRegistry.CertificateStructOutput],
      'view'
    >
    

    
    isCertificateUsable: TypedContractMethod<
      [certificateId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerCertificate: TypedContractMethod<
      [certificateId: BytesLike, assetId: BytesLike, claimType: BytesLike, policyId: BytesLike, evidenceRoot: BytesLike, observedAt: BigNumberish, validUntil: BigNumberish, independentRootCount: BigNumberish, result: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeCertificate: TypedContractMethod<
      [certificateId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setIssuerAuthorization: TypedContractMethod<
      [issuer: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'RESULT_FAIL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'RESULT_INDETERMINATE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'RESULT_PASS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'authorizedIssuers'): TypedContractMethod<
      [issuer: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'certificateExists'): TypedContractMethod<
      [certificateId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getCertificate'): TypedContractMethod<
      [certificateId: BytesLike, ],
      [ProofLayerCertificateRegistry.CertificateStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isCertificateUsable'): TypedContractMethod<
      [certificateId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerCertificate'): TypedContractMethod<
      [certificateId: BytesLike, assetId: BytesLike, claimType: BytesLike, policyId: BytesLike, evidenceRoot: BytesLike, observedAt: BigNumberish, validUntil: BigNumberish, independentRootCount: BigNumberish, result: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeCertificate'): TypedContractMethod<
      [certificateId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setIssuerAuthorization'): TypedContractMethod<
      [issuer: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CertificateRegistered'): TypedContractEvent<CertificateRegisteredEvent.InputTuple, CertificateRegisteredEvent.OutputTuple, CertificateRegisteredEvent.OutputObject>;
getEvent(key: 'CertificateRevoked'): TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;
getEvent(key: 'IssuerAuthorizationUpdated'): TypedContractEvent<IssuerAuthorizationUpdatedEvent.InputTuple, IssuerAuthorizationUpdatedEvent.OutputTuple, IssuerAuthorizationUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'CertificateRegistered(bytes32,bytes32,bytes32,bytes32,bytes32,uint64,uint64,uint32,uint8,address)': TypedContractEvent<CertificateRegisteredEvent.InputTuple, CertificateRegisteredEvent.OutputTuple, CertificateRegisteredEvent.OutputObject>;
      CertificateRegistered: TypedContractEvent<CertificateRegisteredEvent.InputTuple, CertificateRegisteredEvent.OutputTuple, CertificateRegisteredEvent.OutputObject>;
    

      'CertificateRevoked(bytes32,address)': TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;
      CertificateRevoked: TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;
    

      'IssuerAuthorizationUpdated(address,bool)': TypedContractEvent<IssuerAuthorizationUpdatedEvent.InputTuple, IssuerAuthorizationUpdatedEvent.OutputTuple, IssuerAuthorizationUpdatedEvent.OutputObject>;
      IssuerAuthorizationUpdated: TypedContractEvent<IssuerAuthorizationUpdatedEvent.InputTuple, IssuerAuthorizationUpdatedEvent.OutputTuple, IssuerAuthorizationUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }