/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ProofLayerPolicyGateInterface extends Interface {
    getFunction(nameOrSignature: "computeDecisionId" | "decisionLog" | "executeVerifiedAction" | "executedActionCount" | "registry" | "validateAction"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "VerifiedActionExecuted"): EventFragment;

    encodeFunctionData(functionFragment: 'computeDecisionId', values: [BigNumberish, BytesLike, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'decisionLog', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeVerifiedAction', values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'executedActionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'registry', values?: undefined): string;
encodeFunctionData(functionFragment: 'validateAction', values: [BytesLike, BytesLike, BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'computeDecisionId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decisionLog', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeVerifiedAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executedActionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateAction', data: BytesLike): Result;
  }

  
    export namespace VerifiedActionExecutedEvent {
      export type InputTuple = [certificateId: BytesLike, decisionId: BytesLike, actor: AddressLike, actionType: BytesLike, executionNumber: BigNumberish];
      export type OutputTuple = [certificateId: string, decisionId: string, actor: string, actionType: string, executionNumber: bigint];
      export interface OutputObject {certificateId: string, decisionId: string, actor: string, actionType: string, executionNumber: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ProofLayerPolicyGate extends BaseContract {
    
    connect(runner?: ContractRunner | null): ProofLayerPolicyGate;
    waitForDeployment(): Promise<this>;

    interface: ProofLayerPolicyGateInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    computeDecisionId: TypedContractMethod<
      [executionNumber: BigNumberish, certificateId: BytesLike, actor: AddressLike, actionType: BytesLike, ],
      [string],
      'view'
    >
    

    
    decisionLog: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    executeVerifiedAction: TypedContractMethod<
      [certificateId: BytesLike, expectedAssetId: BytesLike, expectedClaimType: BytesLike, expectedPolicyId: BytesLike, actionType: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    executedActionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    registry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    validateAction: TypedContractMethod<
      [certificateId: BytesLike, expectedAssetId: BytesLike, expectedClaimType: BytesLike, expectedPolicyId: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'computeDecisionId'): TypedContractMethod<
      [executionNumber: BigNumberish, certificateId: BytesLike, actor: AddressLike, actionType: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'decisionLog'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'executeVerifiedAction'): TypedContractMethod<
      [certificateId: BytesLike, expectedAssetId: BytesLike, expectedClaimType: BytesLike, expectedPolicyId: BytesLike, actionType: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executedActionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'validateAction'): TypedContractMethod<
      [certificateId: BytesLike, expectedAssetId: BytesLike, expectedClaimType: BytesLike, expectedPolicyId: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'VerifiedActionExecuted'): TypedContractEvent<VerifiedActionExecutedEvent.InputTuple, VerifiedActionExecutedEvent.OutputTuple, VerifiedActionExecutedEvent.OutputObject>;

    filters: {
      
      'VerifiedActionExecuted(bytes32,bytes32,address,bytes32,uint256)': TypedContractEvent<VerifiedActionExecutedEvent.InputTuple, VerifiedActionExecutedEvent.OutputTuple, VerifiedActionExecutedEvent.OutputObject>;
      VerifiedActionExecuted: TypedContractEvent<VerifiedActionExecutedEvent.InputTuple, VerifiedActionExecutedEvent.OutputTuple, VerifiedActionExecutedEvent.OutputObject>;
    
    };
  }